<?php
/* Smarty version 5.4.1, created on 2024-10-16 23:14:15
  from 'string:<p>connect.sampidia.com respects the intellectual property of others, and we ask our users to do the same. Sampidia.com will respond to allegations of copyright violations following the Digital Millennium Copyright Act.</p>
<p>These Terms of Use described the legally binding terms and conditions that oversee your use of the Site.&nbsp;BY LOGGING INTO THE SITE, YOU ARE BEING COMPLIANT THAT THESE TERMS and you represent that you have the authority and capacity to enter into these Terms.&nbsp;YOU SHOULD BE AT LEAST 18 YEARS OF AGE TO ACCESS THE SITE. IF YOU DISAGREE WITH ALL OF THE PROVISION OF THESE TERMS, DO NOT LOG INTO AND/OR USE THE SITE.</p>
<p>These terms require the use of arbitration Section 10.2 on an individual basis to resolve disputes and also limit the remedies available to you in the event of a dispute.</p>
<h2>Access to the Site</h2>
<p><strong>Subject to these Terms.</strong> Company grants you a non-transferable, non-exclusive, revocable, limited license to access the Site solely for your own personal, noncommercial use.</p>
<p><strong>Certain Restrictions.</strong> The rights approved to you in these Terms are subject to the following restrictions: (a) you shall not sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site; (b) you shall not change, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (c) you shall not access the Site in order to build a similar or competitive website; and (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms.&nbsp; All copyright and other proprietary notices on the Site must be retained on all copies thereof.</p>
<h2>User Content</h2>
<p><strong>User Content.</strong> "User Content" means any and all information and content that a user submits to the Site. You are exclusively responsible for your User Content. You bear all risks associated with use of your User Content.&nbsp; You hereby certify that your User Content does not violate our Acceptable Use Policy.&nbsp; You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by Company. Because you alone are responsible for your User Content, you may expose yourself to liability.&nbsp;</p>
<p><strong>Acceptable Use Policy.</strong> The following terms constitute our "Acceptable Use Policy": You agree not to use the Site to collect, upload, transmit, display, or distribute any User Content (i) that violates any third-party right or any intellectual property or proprietary right; (ii) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another&rsquo;s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive, promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual; (iii) that is harmful to minors in any way; or (iv) that is in violation of any law, regulation, or obligations or restrictions imposed by any third party.</p>
<p>If you provide Company with any feedback or suggestions regarding the Site, you hereby assign to Company all rights in such Feedback and agree that Company shall have the right to use and fully exploit such Feedback and related information in any manner it believes appropriate.&nbsp; Company will treat any Feedback you provide to Company as non-confidential and non-proprietary.</p>
<h2>Third-Party Links &amp; Ads; Other Users</h2>
<p><strong>Third-Party Links &amp; Ads.</strong> The Site may contain links to third-party websites and services, and/or display advertisements for third-parties.&nbsp; Such Third-Party Links &amp; Ads are not under the control of Company, and Company is not responsible for any Third-Party Links &amp; Ads.&nbsp;</p>
<p><strong>Other Users.</strong> Each Site user is solely responsible for any and all of its own User Content.&nbsp; Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others.&nbsp; You agree that Company will not be responsible for any loss or damage incurred as the result of any such interactions.&nbsp; If there is a dispute between you and any Site user, we are under no obligation to become involved.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>' */

/* @var \Smarty\Template $_smarty_tpl */
if ($_smarty_tpl->getCompiled()->isFresh($_smarty_tpl, array (
  'version' => '5.4.1',
  'unifunc' => 'content_671048c7100568_12572257',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
  ),
  'includes' => 
  array (
  ),
))) {
function content_671048c7100568_12572257 (\Smarty\Template $_smarty_tpl) {
$_smarty_current_dir = '.';
?><p>connect.sampidia.com respects the intellectual property of others, and we ask our users to do the same. Sampidia.com will respond to allegations of copyright violations following the Digital Millennium Copyright Act.</p>
<p>These Terms of Use described the legally binding terms and conditions that oversee your use of the Site.&nbsp;BY LOGGING INTO THE SITE, YOU ARE BEING COMPLIANT THAT THESE TERMS and you represent that you have the authority and capacity to enter into these Terms.&nbsp;YOU SHOULD BE AT LEAST 18 YEARS OF AGE TO ACCESS THE SITE. IF YOU DISAGREE WITH ALL OF THE PROVISION OF THESE TERMS, DO NOT LOG INTO AND/OR USE THE SITE.</p>
<p>These terms require the use of arbitration Section 10.2 on an individual basis to resolve disputes and also limit the remedies available to you in the event of a dispute.</p>
<h2>Access to the Site</h2>
<p><strong>Subject to these Terms.</strong> Company grants you a non-transferable, non-exclusive, revocable, limited license to access the Site solely for your own personal, noncommercial use.</p>
<p><strong>Certain Restrictions.</strong> The rights approved to you in these Terms are subject to the following restrictions: (a) you shall not sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site; (b) you shall not change, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (c) you shall not access the Site in order to build a similar or competitive website; and (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms.&nbsp; All copyright and other proprietary notices on the Site must be retained on all copies thereof.</p>
<h2>User Content</h2>
<p><strong>User Content.</strong> "User Content" means any and all information and content that a user submits to the Site. You are exclusively responsible for your User Content. You bear all risks associated with use of your User Content.&nbsp; You hereby certify that your User Content does not violate our Acceptable Use Policy.&nbsp; You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by Company. Because you alone are responsible for your User Content, you may expose yourself to liability.&nbsp;</p>
<p><strong>Acceptable Use Policy.</strong> The following terms constitute our "Acceptable Use Policy": You agree not to use the Site to collect, upload, transmit, display, or distribute any User Content (i) that violates any third-party right or any intellectual property or proprietary right; (ii) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another&rsquo;s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive, promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual; (iii) that is harmful to minors in any way; or (iv) that is in violation of any law, regulation, or obligations or restrictions imposed by any third party.</p>
<p>If you provide Company with any feedback or suggestions regarding the Site, you hereby assign to Company all rights in such Feedback and agree that Company shall have the right to use and fully exploit such Feedback and related information in any manner it believes appropriate.&nbsp; Company will treat any Feedback you provide to Company as non-confidential and non-proprietary.</p>
<h2>Third-Party Links &amp; Ads; Other Users</h2>
<p><strong>Third-Party Links &amp; Ads.</strong> The Site may contain links to third-party websites and services, and/or display advertisements for third-parties.&nbsp; Such Third-Party Links &amp; Ads are not under the control of Company, and Company is not responsible for any Third-Party Links &amp; Ads.&nbsp;</p>
<p><strong>Other Users.</strong> Each Site user is solely responsible for any and all of its own User Content.&nbsp; Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others.&nbsp; You agree that Company will not be responsible for any loss or damage incurred as the result of any such interactions.&nbsp; If there is a dispute between you and any Site user, we are under no obligation to become involved.</p>
<p>&nbsp;</p>
<p>&nbsp;</p><?php }
}
